# Example 1
# RUN pip3 install --no-cache-dir paramiko

# Example 2
# COPY python3-requirements.txt /etc/
# RUN pip3 install --no-cache-dir -r /etc/python3-requirements.txt
# RUN rm /etc/python3-requirements.txt)0))
